var MathJaxMap = {};


MathJaxMap['math_1'] = '<math display=\'block\'><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>3</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>333</mn></mrow></math>';
MathJaxMap['math_2'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mi>A</mi><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mi>count</mi><mi>of</mi><mi>outcomes</mi><mi>in</mi></mrow><mi>A</mi></mrow><mrow><mrow><mi>count</mi><mi>of</mi><mi>outcomes</mi><mi>in</mi></mrow><mi>S</mi></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mi>count</mi><mi>of</mi><mi>outcomes</mi><mi>in</mi></mrow><mi>A</mi></mrow><mrow><mi>k</mi></mrow></mfrac></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_3'] = '<math display=\'block\'><mfrac><mrow><mn>1</mn></mrow><mrow><mn>8500</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mrow><mn>1</mn></mrow></mrow><mrow><mn>8500</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mrow><mn>72</mn><mi>,</mi><mn>250</mn><mi>,</mi><mn>000</mn></mrow></mrow></mfrac></math>';
MathJaxMap['math_4'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_5'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mi>HTTH</mi><mo>)</mo><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>16</mn></mrow></mfrac></math>';
MathJaxMap['math_6'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mi>X</mi><mo>=</mo><mn>0</mn><mo>)</mo><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>16</mn></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>0625</mn></mrow></math>';
MathJaxMap['math_7'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mi>X</mi><mo>=</mo><mn>2</mn><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mi>count</mi><mi>of</mi><mi>ways</mi></mrow><mi>X</mi><mo>=</mo><mrow><mn>2</mn><mi>can</mi><mi>occur</mi></mrow></mrow><mrow><mn>16</mn></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mn>6</mn></mrow><mrow><mn>16</mn></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>375</mn></mrow></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_8'] = '<math display=\'block\'><mi>Z</mi><mo>=</mo><mfrac><mrow><mi>X</mi><mo>&#x2212;</mo><mn>&#x3bc;</mn></mrow><mrow><mn>&#x3c3;</mn></mrow></mfrac></math>';
MathJaxMap['math_9'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></math>';
MathJaxMap['math_10'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></math>';
MathJaxMap['math_11'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></math>';
MathJaxMap['math_12'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></math>';
MathJaxMap['math_13'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></math>';
MathJaxMap['math_14'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mn>0</mn><mi>.</mi><mn>23</mn></mrow><mo>&#x2264;</mo><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover><mo>&#x2264;</mo><mrow><mn>0</mn><mi>.</mi><mn>29</mn></mrow><mo>)</mo><mo>=</mo><mi>P</mi><mo>(</mo><mfrac><mrow><mrow><mn>0</mn><mi>.</mi><mn>23</mn></mrow><mo>&#x2212;</mo><mrow><mn>0</mn><mi>.</mi><mn>26</mn></mrow></mrow><mrow><mrow><mn>0</mn><mi>.</mi><mn>0196</mn></mrow></mrow></mfrac><mo>&#x2264;</mo><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover><mo>&#x2212;</mo><mrow><mn>0</mn><mi>.</mi><mn>26</mn></mrow></mrow><mrow><mrow><mn>0</mn><mi>.</mi><mn>0196</mn></mrow></mrow></mfrac><mo>&#x2264;</mo><mfrac><mrow><mrow><mn>0</mn><mi>.</mi><mn>29</mn></mrow><mo>&#x2212;</mo><mrow><mn>0</mn><mi>.</mi><mn>26</mn></mrow></mrow><mrow><mrow><mn>0</mn><mi>.</mi><mn>0196</mn></mrow></mrow></mfrac><mo>)</mo></math>';
MathJaxMap['math_15'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></math>';
MathJaxMap['math_16'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_17'] = '<math display=\'inline\'><mi>P</mi><mo>(</mo><mn>8</mn><mo>&#x2264;</mo><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover><mo>&#x2264;</mo><mn>10</mn><mo>)</mo></math>';
MathJaxMap['math_18'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_19'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></mrow></math>';
MathJaxMap['math_20'] = '<math display=\'inline\'><mi>P</mi><mo>(</mo><mrow><mn>0</mn><mi>.</mi><mn>52</mn></mrow><mo>&#x2264;</mo><mrow><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></mrow><mo>&#x2264;</mo><mrow><mn>0</mn><mi>.</mi><mn>60</mn></mrow><mo>)</mo></math>';
MathJaxMap['math_21'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></mrow></math>';
MathJaxMap['math_22'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></mrow><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>72</mn></mrow></math>';
MathJaxMap['math_23'] = '<math display=\'inline\'><mi>P</mi><mo>(</mo><mrow><mover accent=\'true\'><mi>p</mi><mo stretchy=\'true\'>&#x005E;</mo></mover></mrow><mo>&#x2265;</mo><mrow><mn>0</mn><mi>.</mi><mn>72</mn></mrow><mo>)</mo></math>';
MathJaxMap['math_24'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_25'] = '<math display=\'block\'><mrow><mo>&#x24;</mo><mn>500</mn></mrow><mfrac><mrow><mn>1</mn></mrow><mrow><mn>1000</mn></mrow></mfrac><mo>+</mo><mrow><mo>&#x24;</mo><mn>0</mn></mrow><mfrac><mrow><mn>999</mn></mrow><mrow><mn>1000</mn></mrow></mfrac><mo>=</mo><mrow><mo>&#x24;</mo><mn>0</mn><mi>.</mi><mn>50</mn></mrow></math>';
MathJaxMap['math_26'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_27'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_28'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x3bc;</mi><mi>X</mi></msub></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mn>1</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>2</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>3</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>4</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>5</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mo>+</mo><mn>6</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>7</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>8</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>+</mo><mn>9</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mn>45</mn><mo>&#x00D7;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>9</mn></mrow></mfrac><mo>=</mo><mn>5</mn></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_29'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_30'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_31'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_32'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_33'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_34'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_35'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_36'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_37'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_38'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_39'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_40'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_41'] = '<math display=\'block\'><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover><mo>=</mo><mfrac><mrow><mrow><mn>64</mn><mi>.</mi><mn>21</mn></mrow><mo>+</mo><mrow><mn>64</mn><mi>.</mi><mn>35</mn></mrow></mrow><mrow><mn>2</mn></mrow></mfrac><mo>=</mo><mrow><mn>64</mn><mi>.</mi><mn>28</mn></mrow></math>';
MathJaxMap['math_42'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_43'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>x</mi><mo stretchy=\'true\'>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_44'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_45'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_46'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup></math>';
MathJaxMap['math_47'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_48'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_49'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_50'] = '<math display=\'inline\'><msub><mn>&#x3c3;</mn><mi>X</mi></msub><mo>=</mo><msqrt><mrow><mrow><mn>1</mn><mi>.</mi></mrow><mpadded><mn>662</mn></mpadded></mrow></msqrt><mo>=</mo><mrow><mn>1</mn><mi>.</mi></mrow><mpadded><mn>289</mn></mpadded></math>';
MathJaxMap['math_51'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_52'] = '<math display=\'block\'><msubsup><mn>&#x3c3;</mn><mrow><mi>a</mi><mo>+</mo><mi>bX</mi></mrow><mn>2</mn></msubsup><mo>=</mo><msup><mi>b</mi><mn>2</mn></msup><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup></math>';
MathJaxMap['math_53'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_54'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup><mo>+</mo><mn>2</mn><mo>&#x3c1;</mo><msub><mn>&#x3c3;</mn><mi>X</mi></msub><msub><mn>&#x3c3;</mn><mi>Y</mi></msub></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup><mo>&#x2212;</mo><mn>2</mn><mo>&#x3c1;</mo><msub><mn>&#x3c3;</mn><mi>X</mi></msub><msub><mn>&#x3c3;</mn><mi>Y</mi></msub></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_55'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_56'] = '<math display=\'inline\'><mn>4</mn><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup></math>';
MathJaxMap['math_57'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_58'] = '<math display=\'inline\'><msub><mn>&#x3c3;</mn><mi>X</mi></msub><mo>=</mo><msqrt><mrow><mrow><mn>249</mn><mi>.</mi><mn>75</mn></mrow></mrow></msqrt><mo>=</mo></math>';
MathJaxMap['math_59'] = '<math display=\'block\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow><mn>2</mn></msubsup><mo>=</mo><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup><mo>=</mo><mrow><mn>249</mn><mi>.</mi><mn>75</mn></mrow><mo>+</mo><mrow><mn>249</mn><mi>.</mi><mn>75</mn></mrow><mo>=</mo><mrow><mn>499</mn><mi>.</mi><mn>5</mn></mrow></math>';
MathJaxMap['math_60'] = '<math display=\'block\'><msub><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow></msub><mo>=</mo><msqrt><mrow><mrow><mn>499</mn><mi>.</mi><mn>5</mn></mrow></mrow></msqrt><mo>=</mo><mrow><mo>&#x24;</mo><mn>22</mn><mi>.</mi><mn>35</mn></mrow></math>';
MathJaxMap['math_61'] = '<math display=\'block\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow><mn>2</mn></msubsup><mo>=</mo><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup><mo>+</mo><mn>2</mn><mo>&#x3c1;</mo><msub><mn>&#x3c3;</mn><mi>X</mi></msub><msub><mn>&#x3c3;</mn><mi>Y</mi></msub></math>';
MathJaxMap['math_62'] = '<math display=\'block\'><msub><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow></msub><mo>=</mo><msqrt><mrow><mrow><mn>3923</mn><mi>.</mi><mn>5</mn></mrow></mrow></msqrt><mo>=</mo><mn>63</mn></math>';
MathJaxMap['math_63'] = '<math display=\'block\'><msubsup><mn>&#x3c3;</mn><mi>S</mi><mn>2</mn></msubsup><mo>=</mo><msup><mn>1000</mn><mn>2</mn></msup><msup><mrow><mo>(</mo><mrow><mn>0</mn><mi>.</mi><mn>22</mn></mrow><mo>)</mo></mrow><mn>2</mn></msup><mo>=</mo><mrow><mn>48</mn><mi>,</mi><mn>400</mn></mrow></math>';
MathJaxMap['math_64'] = '<math display=\'block\'><msub><mn>&#x3c3;</mn><mi>S</mi></msub><mo>=</mo><msqrt><mrow><mrow><mn>48</mn><mi>,</mi><mn>400</mn></mrow></mrow></msqrt><mo>=</mo><mn>220</mn></math>';
MathJaxMap['math_65'] = '<math display=\'block\'><msubsup><mn>&#x3c3;</mn><mrow><mi>S</mi><mo>+</mo><mi>D</mi></mrow><mn>2</mn></msubsup><mo>=</mo><msubsup><mn>&#x3c3;</mn><mi>S</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>D</mi><mn>2</mn></msubsup><mo>+</mo><mn>2</mn><mo>&#x3c1;</mo><mrow><msub><mn>&#x3c3;</mn><mi>S</mi></msub></mrow><msub><mn>&#x3c3;</mn><mi>D</mi></msub><mo>=</mo><msup><mrow><mo>(</mo><mn>220</mn><mo>)</mo></mrow><mn>2</mn></msup><mo>+</mo><msup><mrow><mo>(</mo><mn>330</mn><mo>)</mo></mrow><mn>2</mn></msup><mo>+</mo><mn>2</mn><mo>(</mo><mrow><mn>0</mn><mi>.</mi><mn>68</mn></mrow><mo>)</mo><mo>(</mo><mn>220</mn><mo>)</mo><mo>(</mo><mn>330</mn><mo>)</mo><mo>=</mo><mrow><mn>256</mn><mi>,</mi><mn>036</mn></mrow></math>';
MathJaxMap['math_66'] = '<math display=\'block\'><msub><mn>&#x3c3;</mn><mrow><mi>S</mi><mo>+</mo><mi>D</mi></mrow></msub><mo>=</mo><msqrt><mrow><mrow><mn>256</mn><mi>,</mi><mn>036</mn></mrow></mrow></msqrt><mo>=</mo><mn>506</mn></math>';
MathJaxMap['math_67'] = '<math display=\'inline\'><msubsup><mn>&#x3c3;</mn><mn>2</mn><mi>X</mi></msubsup></math>';
MathJaxMap['math_68'] = '<math display=\'block\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>=</mo><msup><mrow><mo>(</mo><msub><mi>x</mi><mn>1</mn></msub><mo>&#x2212;</mo><msub><mn>&#x3bc;</mn><mi>X</mi></msub><mo>)</mo></mrow><mn>2</mn></msup><msub><mi>p</mi><mn>1</mn></msub><mo>+</mo><msup><mrow><mo>(</mo><msub><mi>x</mi><mn>2</mn></msub><mo>&#x2212;</mo><msub><mn>&#x3bc;</mn><mi>X</mi></msub><mo>)</mo></mrow><mn>2</mn></msup><msub><mi>p</mi><mn>2</mn></msub><mo>+</mo><mo>&#8230;</mo></math>';
MathJaxMap['math_69'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msub><mn>&#x3bc;</mn><mrow><mi>a</mi><mo>+</mo><mi>bX</mi></mrow></msub></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mi>a</mi><mo>+</mo><mi>b</mi><msub><mn>&#x3bc;</mn><mi>X</mi></msub></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>a</mi><mo>+</mo><mi>bX</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msup><mi>b</mi><mn>2</mn></msup><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_70'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msub><mn>&#x3bc;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow></msub></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msub><mn>&#x3bc;</mn><mi>X</mi></msub><mo>+</mo><msub><mn>&#x3bc;</mn><mi>Y</mi></msub></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msub><mn>&#x3bc;</mn><mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi></mrow></msub></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msub><mn>&#x3bc;</mn><mi>X</mi></msub><mo>&#x2212;</mo><msub><mn>&#x3bc;</mn><mi>Y</mi></msub></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup><mo>+</mo><mn>2</mn><mo>&#x3c1;</mo><msub><mn>&#x3c3;</mn><mi>X</mi></msub><msub><mn>&#x3c3;</mn><mi>Y</mi></msub></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup><mo>&#x2212;</mo><mn>2</mn><mo>&#x3c1;</mo><msub><mn>&#x3c3;</mn><mi>X</mi></msub><msub><mn>&#x3c3;</mn><mi>Y</mi></msub></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_71'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi></mrow><mn>2</mn></msubsup></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><msubsup><mn>&#x3c3;</mn><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mn>&#x3c3;</mn><mi>Y</mi><mn>2</mn></msubsup></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_72'] = '<math display=\'inline\'><msub><mn>&#x3c3;</mn><mrow><mi>X</mi><mo>+</mo><mi>Y</mi></mrow></msub><mo>=</mo><msub><mn>&#x3c3;</mn><mi>X</mi></msub><mo>+</mo><msub><mn>&#x3c3;</mn><mi>Y</mi></msub></math>';
MathJaxMap['math_73'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mi>heart</mi><mo>)</mo><mo>=</mo><mfrac><mrow><mn>13</mn></mrow><mrow><mn>52</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac></math>';
MathJaxMap['math_74'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mi>heart</mi></mrow><mo>&#x7c;</mo><mrow><mn>4</mn><mi>hearts</mi><mi>in</mi><mn>4</mn><mi>visible</mi><mi>cards</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mn>9</mn></mrow><mrow><mn>48</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>3</mn></mrow><mrow><mn>16</mn></mrow></mfrac></math>';
MathJaxMap['math_75'] = '<math display=\'block\'><mtable><mtr><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mrow><mi>first</mi><mi>card</mi><mi>is</mi><mi>a</mi><mi>heart</mi></mrow><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mn>11</mn></mrow><mrow><mn>28</mn></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mrow><mi>second</mi><mi>card</mi><mi>is</mi><mi>a</mi><mi>heart</mi></mrow><mo>&#x7c;</mo><mrow><mi>first</mi><mi>card</mi><mi>is</mi><mi>a</mi><mi>heart</mi></mrow><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mn>10</mn></mrow><mrow><mn>27</mn></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mrow><mi>third</mi><mi>card</mi><mi>is</mi><mi>a</mi><mi>heart</mi></mrow><mo>&#x7c;</mo><mrow><mi>first</mi><mi>two</mi><mi>cards</mi><mi>are</mi><mi>hearts</mi></mrow><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mn>9</mn></mrow><mrow><mn>26</mn></mrow></mfrac></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_76'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mi>next</mi><mi>two</mi><mi>cards</mi><mi>are</mi><mi>hearts</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mn>11</mn></mrow><mrow><mn>28</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mn>10</mn></mrow><mrow><mn>27</mn></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>146</mn></mrow></math>';
MathJaxMap['math_77'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mi>next</mi><mi>three</mi><mi>cards</mi><mi>are</mi><mi>hearts</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mn>11</mn></mrow><mrow><mn>28</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mn>10</mn></mrow><mrow><mn>27</mn></mrow></mfrac><mo>&#x00D7;</mo><mfrac><mrow><mn>9</mn></mrow><mrow><mn>26</mn></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>050</mn></mrow></math>';
MathJaxMap['math_78'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mi>B</mi></mrow><mo>&#x7c;</mo><mrow><mi>A</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mi>P</mi><mo>(</mo><mrow><mi>A</mi></mrow><mrow><mi>and</mi></mrow><mi>B</mi><mo>)</mo></mrow><mrow><mi>P</mi><mo>(</mo><mi>A</mi><mo>)</mo></mrow></mfrac></math>';
MathJaxMap['math_79'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mi>A</mi></mrow><mo>&#x7c;</mo><mrow><mi>B</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mi>P</mi><mo>(</mo><mrow><mi>A</mi></mrow><mrow><mi>and</mi></mrow><mi>B</mi><mo>)</mo></mrow><mrow><mi>P</mi><mo>(</mo><mi>B</mi><mo>)</mo></mrow></mfrac></math>';
MathJaxMap['math_80'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mrow><mi>A</mi></mrow><mo>&#x7c;</mo><mrow><mi>B</mi></mrow><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mi>P</mi><mo>(</mo><mrow><mi>A</mi></mrow><mrow><mi>and</mi></mrow><mi>B</mi><mo>)</mo></mrow><mrow><mi>P</mi><mo>(</mo><mi>B</mi><mo>)</mo></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mn>0</mn><mi>.</mi><mn>32</mn></mrow></mrow><mrow><mrow><mn>0</mn><mi>.</mi><mn>68</mn></mrow></mrow></mfrac></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_81'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>P</mi><mo>(</mo><mrow><msub><mi>A</mi><mn>1</mn></msub></mrow><mo>&#x7c;</mo><mrow><mi>C</mi></mrow><mo>)</mo></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mi>P</mi><mo>(</mo><msub><mi>A</mi><mn>1</mn></msub><mrow><mi>and</mi></mrow><mi>C</mi><mo>)</mo></mrow><mrow><mi>P</mi><mo>(</mo><mi>C</mi><mo>)</mo></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'></mstyle></mtd><mtd><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\"left\"><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mn>0</mn><mi>.</mi><mn>1363</mn></mrow></mrow><mrow><mrow><mn>0</mn><mi>.</mi><mn>2518</mn></mrow></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mi>.</mi><mn>5413</mn></mrow></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_82'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><msub><mi>A</mi><mi>i</mi></msub><mo>&#x7c;</mo><mrow><mi>C</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mi>P</mi><mo>(</mo><mrow><mi>C</mi></mrow><mo>&#x7c;</mo><msub><mi>A</mi><mi>i</mi></msub><mo>)</mo><mi>P</mi><mo>(</mo><msub><mi>A</mi><mi>i</mi></msub><mo>)</mo></mrow><mrow><mi>P</mi><mo>(</mo><mrow><mi>C</mi></mrow><mo>&#x7c;</mo><msub><mi>A</mi><mn>1</mn></msub><mo>)</mo><mi>P</mi><mo>(</mo><msub><mi>A</mi><mn>1</mn></msub><mo>)</mo><mo>+</mo><mi>P</mi><mo>(</mo><mrow><mi>C</mi></mrow><mo>&#x7c;</mo><msub><mi>A</mi><mn>2</mn></msub><mo>)</mo><mi>P</mi><mo>(</mo><msub><mi>A</mi><mn>2</mn></msub><mo>)</mo><mo>+</mo><mo>&#x2026;</mo><mo>+</mo><mi>P</mi><mo>(</mo><msub><mi>A</mi><mi>k</mi></msub><mo>)</mo><mi>P</mi><mo>(</mo><mrow><mi>C</mi></mrow><mo>&#x7c;</mo><msub><mi>A</mi><mi>k</mi></msub><mo>)</mo></mrow></mfrac></math>';
MathJaxMap['math_83'] = '<math display=\'block\'><mi>P</mi><mo>(</mo><mrow><mi>B</mi></mrow><mo>&#x7c;</mo><mrow><mi>A</mi></mrow><mo>)</mo><mo>=</mo><mfrac><mrow><mi>P</mi><mo>(</mo><mrow><mi>A</mi></mrow><mrow><mi>and</mi></mrow><mi>B</mi><mo>)</mo></mrow><mrow><mi>P</mi><mo>(</mo><mi>A</mi><mo>)</mo></mrow></mfrac></math>';



for (var key in MathJaxMap) {
  
  if (MathJaxMap.hasOwnProperty(key)) {
    $('[data-math=' + key + ']').html(MathJaxMap[key]);
  }
}

$.ajaxSetup({
  cache: true
});

//configure the mathjax engine
window.MathJax = {
	"HTML-CSS": {
		mtextFontInherit: true,
		scale: 98,
		minScaleAdjust: 100,
		noReflows:false 
	},
	MathML: {
		useMathMLspacing: false
	},
	menuSettings: {
		zoom: "Click"	
	},
	MathMenu: {
		showFontMenu: true
	}
	
  };

$.getScript( "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"); 
