var MathJaxMap = {};


MathJaxMap['math_1'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>=</mo><mn>19</mn><mo>.</mo><mn>0</mn></math>';
MathJaxMap['math_2'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>=</mo><mn>19</mn><mo>.</mo><mn>0</mn></math>';
MathJaxMap['math_3'] = '<math display=\'block\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mfrac><mrow><mn>1056</mn></mrow><mrow><mn>1200</mn></mrow></mfrac><mo>=</mo><mn>0</mn><mo>.</mo><mn>88</mn><mo>=</mo><mrow><mn>88</mn><mo>&#x25;</mo></mrow></math>';
MathJaxMap['math_4'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_5'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_6'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_7'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_8'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_9'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mn>90</mn><mo>/</mo><mn>100</mn><mo>=</mo><mn>0</mn><mo>.</mo><mn>90</mn></math>';
MathJaxMap['math_10'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mn>0</mn><mo>.</mo><mn>86</mn></math>';
MathJaxMap['math_11'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mn>0</mn><mo>.</mo><mn>92</mn></math>';
MathJaxMap['math_12'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_13'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_14'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_15'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_16'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_17'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_18'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_19'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_20'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_21'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_22'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_23'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_24'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_25'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_26'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_27'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_28'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_29'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_30'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_31'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_32'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_33'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_34'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_35'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_36'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_37'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_38'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_39'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_40'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_41'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_42'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_43'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_44'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_45'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_46'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_47'] = '<math display=\'block\'><mrow><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>=</mo><mfrac><mn>1</mn><mi>n</mi></mfrac><mrow><mo>(</mo><mrow><msub><mi>X</mi><mn>1</mn></msub><mo>+</mo><msub><mi>X</mi><mn>2</mn></msub><mo>+</mo><mo>&#x22EF;</mo><msub><mi>X</mi><mi>n</mi></msub></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_48'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_49'] = '<math display=\'block\'><mtable><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub><mo>=</mo><mfrac><mn>1</mn><mi>n</mi></mfrac><mrow><mo>(</mo><mrow><msub><mi>&#x03BC;</mi><mrow><msub><mi>X</mi><mn>1</mn></msub></mrow></msub><mo>+</mo><msub><mi>&#x03BC;</mi><mrow><msub><mi>X</mi><mn>2</mn></msub></mrow></msub><mo>+</mo><mo>&#x22EF;</mo><mo>+</mo><msub><mi>&#x03BC;</mi><mrow><msub><mi>X</mi><mi>n</mi></msub></mrow></msub></mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mo>=</mo><mfrac><mn>1</mn><mi>n</mi></mfrac><mrow><mo>(</mo><mrow><mi>&#x03BC;</mi><mo>+</mo><mi>&#x03BC;</mi><mo>+</mo><mo>&#x22EF;</mo><mo>+</mo><mi>&#x03BC;</mi></mrow><mo>)</mo></mrow><mo>=</mo><mi>&#x03BC;</mi></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_50'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_51'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_52'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><msubsup><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mn>2</mn></msubsup></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msup><mrow><mo>(</mo><mrow><mfrac><mn>1</mn><mi>n</mi></mfrac></mrow><mo>)</mo></mrow><mn>2</mn></msup><mrow><mo>(</mo><mrow><msubsup><mi>&#x03C3;</mi><mrow><msub><mi>X</mi><mn>1</mn></msub></mrow><mn>2</mn></msubsup><mo>+</mo><msubsup><mi>&#x03C3;</mi><mrow><msub><mi>X</mi><mn>2</mn></msub></mrow><mn>2</mn></msubsup><mo>+</mo><mo>&#x22EF;</mo><mo>+</mo><msubsup><mi>&#x03C3;</mi><mrow><msub><mi>X</mi><mi>n</mi></msub></mrow><mn>2</mn></msubsup></mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msup><mrow><mo>(</mo><mrow><mfrac><mn>1</mn><mi>n</mi></mfrac></mrow><mo>)</mo></mrow><mn>2</mn></msup><mrow><mo>(</mo><mrow><msup><mi>&#x03C3;</mi><mn>2</mn></msup><mo>+</mo><msup><mi>&#x03C3;</mi><mn>2</mn></msup><mo>+</mo><mo>&#x22EF;</mo><mo>+</mo><msup><mi>&#x03C3;</mi><mn>2</mn></msup></mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><msup><mi>&#x03C3;</mi><mn>2</mn></msup></mrow><mi>n</mi></mfrac></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_53'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_54'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_55'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_56'] = '<math display=\'block\'><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub><mo>=</mo><mi>&#x03BC;</mi></math>';
MathJaxMap['math_57'] = '<math display=\'block\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub><mo>=</mo><mfrac><mrow><mi>&#x03C3;</mi></mrow><mrow><msqrt><mrow><mi>n</mi></mrow></msqrt></mrow></mfrac></math>';
MathJaxMap['math_58'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_59'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_60'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_61'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_62'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_63'] = '<math display=\'inline\'><mi>&#x03C3;</mi><mo>/</mo><msqrt><mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_64'] = '<math display=\'block\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub><mo>=</mo><mfrac><mrow><mrow><mn>41</mn><mo>.</mo><mn>84</mn></mrow></mrow><mrow><msqrt><mrow><mn>15</mn></mrow></msqrt></mrow></mfrac><mo>=</mo><mrow><mn>10</mn><mo>.</mo><mn>80</mn><mi>&#x00A0;</mi></mrow><mtext>minutes</mtext></math>';
MathJaxMap['math_65'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_66'] = '<math display=\'block\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub><mo>=</mo><mfrac><mrow><mrow><mn>41</mn><mo>.</mo><mn>84</mn></mrow></mrow><mrow><msqrt><mrow><mn>60</mn></mrow></msqrt></mrow></mfrac><mo>=</mo><mrow><mn>5</mn><mo>.</mo><mn>40</mn><mi>&#x00A0;</mi></mrow><mtext>minutes</mtext></math>';
MathJaxMap['math_67'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_68'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_69'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_70'] = '<math display=\'inline\'><mi>N</mi><mrow><mo>(</mo></mrow><mi>&#x03BC;</mi><mrow><mo>,</mo><mi>&#x00A0;</mi></mrow><mi>&#x03C3;</mi><mo>/</mo><msqrt><mrow><mi>n</mi></mrow></msqrt><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_71'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_72'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_73'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_74'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_75'] = '<math display=\'inline\'><mi>N</mi><mrow><mo>(</mo></mrow><mi>&#x03BC;</mi><mrow><mo>,</mo><mi>&#x00A0;</mi></mrow><mfrac><mrow><mi>&#x03C3;</mi></mrow><mrow><msqrt><mrow><mi>n</mi></mrow></msqrt></mrow></mfrac><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_76'] = '<math display=\'inline\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub><mo>=</mo><mrow><mn>5</mn><mo>.</mo><mn>4</mn></mrow></math>';
MathJaxMap['math_77'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_78'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_79'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_80'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_81'] = '<math display=\'block\'><mrow><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub></mrow><mo>=</mo><mfrac><mrow><mrow><mn>41</mn><mo>.</mo><mn>84</mn></mrow></mrow><mrow><msqrt><mrow><mn>240</mn></mrow></msqrt></mrow></mfrac><mo>=</mo><mrow><mn>2</mn><mo>.</mo><mn>70</mn><mi>&#x00A0;</mi></mrow><mtext>minutes</mtext></math>';
MathJaxMap['math_82'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_83'] = '<math display=\'inline\'><msqrt><mrow><mfrac><mrow><mi>N</mi><mo>&#x2212;</mo><mi>n</mi></mrow><mrow><mi>N</mi><mo>&#x2212;</mo><mn>1</mn></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_84'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_85'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_86'] = '<math display=\'block\'><mfrac><mrow><mrow><mn>41</mn><mo>.</mo><mn>84</mn></mrow></mrow><mrow><msqrt><mrow><mn>240</mn></mrow></msqrt></mrow></mfrac><msqrt><mrow><mfrac><mrow><mn>1264</mn><mo>&#x2212;</mo><mn>240</mn></mrow><mrow><mn>1264</mn><mo>&#x2212;</mo><mn>1</mn></mrow></mfrac></mrow></msqrt><mo>=</mo><mrow><mn>2</mn><mo>.</mo><mn>43</mn><mi>&#x00A0;</mi></mrow><mtext>minutes</mtext></math>';
MathJaxMap['math_87'] = '<math display=\'inline\'><msqrt><mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_88'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_89'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_90'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_91'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_92'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_93'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_94'] = '<math display=\'inline\'><mn>1</mn><mo>/</mo><msqrt><mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_95'] = '<math display=\'inline\'><mi>&#x03C3;</mi><mo>=</mo><mn>1</mn><mo>/</mo><msqrt><mrow><mn>10</mn></mrow></msqrt><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>32</mn></mrow></math>';
MathJaxMap['math_96'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_97'] = '<math display=\'inline\'><mn>1</mn><mo>/</mo><msqrt><mrow><mn>10</mn></mrow></msqrt><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>316</mn></mrow></math>';
MathJaxMap['math_98'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_99'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_100'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_101'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_102'] = '<math display=\'block\'><mfrac><mrow><mi>&#x03C3;</mi></mrow><mrow><msqrt><mrow><mn>50</mn></mrow></msqrt></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>15</mn></mrow><mrow><msqrt><mrow><mn>50</mn></mrow></msqrt></mrow></mfrac><mo>=</mo><mrow><mn>2</mn><mo>.</mo><mn>12</mn><mi>&#x00A0;</mi></mrow><mtext>minutes</mtext></math>';
MathJaxMap['math_103'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_104'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_105'] = '<math display=\'inline\'><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>&#x003E;</mo><mn>13.0</mn></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_106'] = '<math display=\'block\'><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>&#x003E;</mo><mn>13.0</mn></mrow><mo>)</mo></mrow><mo>=</mo><mi>P</mi><mrow><mo>(</mo><mrow><mfrac><mrow><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>&#x2212;</mo><mn>15</mn></mrow><mrow><mn>2.12</mn></mrow></mfrac><mo>&#x003E;</mo><mfrac><mrow><mn>13.0</mn><mo>&#x2212;</mo><mn>15</mn></mrow><mrow><mn>2.12</mn></mrow></mfrac></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_107'] = '<math display=\'block\'><mi>P</mi><mrow><mo>(</mo></mrow><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>&#x003E;</mo><mrow><mn>13</mn><mo>.</mo><mn>0</mn></mrow><mrow><mo>)</mo></mrow><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>8264</mn></mrow></math>';
MathJaxMap['math_108'] = '<math display=\'inline\'><mo>&#x007B;</mo><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>&#x003E;</mo><mrow><mn>13</mn><mo>.</mo><mn>0</mn></mrow><mo>&#x007D;</mo></math>';
MathJaxMap['math_109'] = '<math display=\'inline\'><mo>&#x007B;</mo><mrow><mn>50</mn><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></mrow><mo>&#x003E;</mo><mn>50</mn><mrow><mo>(</mo></mrow><mrow><mn>13</mn><mo>.</mo><mn>0</mn></mrow><mrow><mo>)</mo></mrow><mo>&#x007D;</mo></math>';
MathJaxMap['math_110'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_111'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_112'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_113'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_114'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_115'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_116'] = '<math display=\'inline\'><mi>&#x03C3;</mi><mo>/</mo><msqrt><mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_117'] = '<math display=\'block\'><mrow><msubsup><mi>&#x03C3;</mi><mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi></mrow><mn>2</mn></msubsup><mo>=</mo><msubsup><mi>&#x03C3;</mi><mi>X</mi><mn>2</mn></msubsup><mo>+</mo><msubsup><mi>&#x03C3;</mi><mi>Y</mi><mn>2</mn></msubsup><mo>=</mo><msup><mn>4</mn><mn>2</mn></msup><mo>+</mo><msup><mn>8</mn><mn>2</mn></msup><mo>=</mo><mn>80</mn></mrow></math>';
MathJaxMap['math_118'] = '<math display=\'inline\'><msqrt><mrow><mn>80</mn></mrow></msqrt><mo>=</mo><mrow><mn>8</mn><mo>.</mo><mn>94</mn></mrow></math>';
MathJaxMap['math_119'] = '<math display=\'block\'><mo>=</mo><mi>P</mi><mrow><mo>(</mo></mrow><mfrac><mrow><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2212;</mo><mi>Y</mi><mrow><mo>)</mo></mrow><mo>&#x2212;</mo><mn>2</mn></mrow><mrow><mrow><mn>8</mn><mo>.</mo><mn>94</mn></mrow></mrow></mfrac><mi>&#x00A0;</mi><mo>&#x003C;</mo><mi>&#x00A0;</mi><mfrac><mrow><mn>0</mn><mo>&#x2212;</mo><mn>2</mn></mrow><mrow><mrow><mn>8</mn><mo>.</mo><mn>94</mn></mrow></mrow></mfrac><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_120'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_121'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_122'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_123'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_124'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_125'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_126'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>&#x03BC;</mi></mstyle></mtd></mtr><mtr columnalign=\'left\'><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></msub></mrow></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mfrac><mi>&#x03C3;</mi><mrow><msqrt><mi>n</mi></msqrt></mrow></mfrac></mrow></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_127'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_128'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_129'] = '<math display=\'inline\'><mi>N</mi><mrow><mo>(</mo></mrow><mi>&#x03BC;</mi><mrow><mo>,</mo><mi>&#x00A0;</mi></mrow><mi>&#x03C3;</mi><mo>/</mo><msqrt><mrow><mi>n</mi></mrow></msqrt><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_130'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_131'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_132'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_133'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_134'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_135'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_136'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_137'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_138'] = '<math display=\'inline\'><mi>&#x03C3;</mi><mo>/</mo><msqrt><mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_139'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_140'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_141'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_142'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_143'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_144'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_145'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_146'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_147'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_148'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_149'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_150'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_151'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_152'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover><mo>&#x2265;</mo><mn>3</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_153'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_154'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>y</mi><mo>&#x00AF;</mo></mover><mo>&#x2212;</mo><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_155'] = '<math display=\'inline\'><mover accent=\'true\'><mi>y</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_156'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_157'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>y</mi><mo>&#x00AF;</mo></mover><mo>&#x2212;</mo><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_158'] = '<math display=\'inline\'><mover accent=\'true\'><mi>R</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_159'] = '<math display=\'inline\'><mover accent=\'true\'><mi>R</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_160'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></mrow></math>';
MathJaxMap['math_161'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_162'] = '<math display=\'block\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mfrac><mrow><mn>755</mn></mrow><mrow><mn>1006</mn></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>75</mn></mrow></math>';
MathJaxMap['math_163'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_164'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_165'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_166'] = '<math display=\'block\'><mi>p</mi><mo>=</mo><mfrac><mrow><mn>800</mn></mrow><mrow><mrow><mn>10</mn><mo>,</mo><mn>000</mn></mrow></mrow></mfrac><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>08</mn></mrow></math>';
MathJaxMap['math_167'] = '<math display=\'inline\'><mrow><msubsup><mi>&#x03C3;</mi><mi>S</mi><mn>2</mn></msubsup><mo>=</mo><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_168'] = '<math display=\'inline\'><mrow><msubsup><mi>&#x03C3;</mi><mi>X</mi><mn>2</mn></msubsup><mo>=</mo><mi>n</mi><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_169'] = '<math display=\'block\'><mrow><msub><mi>&#x03C3;</mi><mi>X</mi></msub></mrow><mo>=</mo><msqrt><mrow><mi>n</mi><mi>p</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow></mrow></msqrt></math>';
MathJaxMap['math_170'] = '<math display=\'block\'><mrow><msub><mi>&#x03C3;</mi><mi>X</mi></msub></mrow><mo>=</mo><msqrt><mrow><mi>n</mi><mi>p</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow></mrow></msqrt><mo>=</mo><msqrt><mrow><mrow><mo>(</mo></mrow><mn>2000</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mrow><mn>0</mn><mo>.</mo><mn>04</mn></mrow><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mrow><mn>0</mn><mo>.</mo><mn>96</mn></mrow><mrow><mo>)</mo></mrow></mrow></msqrt><mo>=</mo><mrow><mn>8</mn><mo>.</mo><mn>76</mn></mrow></math>';
MathJaxMap['math_171'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mtext>count</mtext><mi>&#x00A0;</mi><mtext>of</mtext><mi>&#x00A0;</mi><mtext>successes</mtext><mi>&#x00A0;</mi><mtext>in</mtext><mi>&#x00A0;</mi><mtext>sample</mtext></mrow></mrow><mrow><mrow><mtext>size</mtext><mi>&#x00A0;</mi><mtext>of</mtext><mi>&#x00A0;</mi><mtext>sample</mtext></mrow></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mo>=</mo></mrow></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mfrac><mi>X</mi><mi>n</mi></mfrac></mrow></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_172'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_173'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_174'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_175'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mi>X</mi><mo>/</mo><mn>2500</mn></math>';
MathJaxMap['math_176'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_177'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_178'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>&#x2265;</mo><mrow><mn>0</mn><mo>.</mo><mn>58</mn></mrow><mrow><mo>)</mo></mrow><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>9802</mn></mrow></math>';
MathJaxMap['math_179'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_180'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_181'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>p</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mi>n</mi></mfrac></mrow></msqrt></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_182'] = '<math display=\'inline\'><mrow><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></mrow></math>';
MathJaxMap['math_183'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>p</mi><mo>=</mo><mn>0.6</mn></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mi>n</mi></mfrac></mrow></msqrt><mo>=</mo><msqrt><mrow><mfrac><mrow><mrow><mo>(</mo><mrow><mn>0.6</mn></mrow><mo>)</mo></mrow><mrow><mo>(</mo><mrow><mn>0.4</mn></mrow><mo>)</mo></mrow></mrow><mrow><mn>2500</mn></mrow></mfrac></mrow></msqrt><mo>=</mo><mn>0.0098</mn></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_184'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_185'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_186'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_187'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_188'] = '<math display=\'inline\'><msqrt><mrow><mi>p</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow><mo>/</mo><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_189'] = '<math display=\'inline\'><msqrt><mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_190'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_191'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_192'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_193'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_194'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_195'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_196'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_197'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_198'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_199'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_200'] = '<math display=\'block\'><mrow><mi>X</mi><mtext>&#x2009;</mtext><mtext>is</mtext><mtext>&#x2009;</mtext><mtext>approximately</mtext><mtext>&#x2009;</mtext><mi>N</mi><mrow><mo>(</mo><mrow><mi>n</mi><mi>p</mi><mo>,</mo><msqrt><mrow><mi>n</mi><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow></msqrt></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_201'] = '<math display=\'block\'><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mtext>&#x2009;</mtext><mtext>is</mtext><mtext>&#x2009;</mtext><mtext>approximately</mtext><mtext>&#x2009;</mtext><mi>N</mi><mrow><mo>(</mo><mrow><mi>p</mi><mo>,</mo><mtext>&#x2009;</mtext><msqrt><mrow><mfrac><mrow><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mi>n</mi></mfrac></mrow></msqrt></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_202'] = '<math display=\'inline\'><mi>n</mi><mi>p</mi><mo>&#x2265;</mo><mn>10</mn></math>';
MathJaxMap['math_203'] = '<math display=\'inline\'><mi>n</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow><mo>&#x2265;</mo><mn>10</mn></math>';
MathJaxMap['math_204'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_205'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_206'] = '<math display=\'inline\'><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo><mo>/</mo></mrow><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_207'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_208'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_209'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_210'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>&#x2265;</mo><mrow><mn>0</mn><mo>.</mo><mn>58</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_211'] = '<math display=\'inline\'><mi>n</mi><mo>=</mo><mn>2500</mn></math>';
MathJaxMap['math_212'] = '<math display=\'inline\'><mi>p</mi><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>6</mn></mrow></math>';
MathJaxMap['math_213'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>p</mi><mo>=</mo><mn>0.6</mn></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mi>n</mi></mfrac></mrow></msqrt><mo>=</mo><mn>0.0098</mn></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_214'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_215'] = '<math display=\'block\'><mi>P</mi><mrow><mo>(</mo></mrow><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>&#x2265;</mo><mrow><mn>0</mn><mo>.</mo><mn>58</mn></mrow><mrow><mo>)</mo></mrow><mo>=</mo><mi>P</mi><mrow><mo>(</mo></mrow><mfrac><mrow><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>&#x2212;</mo><mrow><mn>0</mn><mo>.</mo><mn>6</mn></mrow></mrow><mrow><mrow><mn>0</mn><mo>.</mo><mn>0098</mn></mrow></mrow></mfrac><mo>&#x2265;</mo><mfrac><mrow><mrow><mn>0</mn><mo>.</mo><mn>58</mn></mrow><mo>&#x2212;</mo><mrow><mn>0</mn><mo>.</mo><mn>6</mn></mrow></mrow><mrow><mrow><mn>0</mn><mo>.</mo><mn>0098</mn></mrow></mrow></mfrac><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_216'] = '<math display=\'inline\'><mi>B</mi><mrow><mo>(</mo></mrow><mrow><mn>150</mn><mo>,</mo><mi>&#x00A0;</mi><mn>0</mn><mo>.</mo><mn>08</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_217'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><msub><mi>&#x03BC;</mi><mi>X</mi></msub></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>n</mi><mi>p</mi><mo>=</mo><mrow><mo>(</mo></mrow><mn>150</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mrow><mn>0</mn><mo>.</mo><mn>08</mn></mrow><mrow><mo>)</mo></mrow><mo>=</mo><mn>12</mn></mstyle></mtd></mtr><mtr columnalign=\'left\'><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msub><mi>&#x03C3;</mi><mi>X</mi></msub></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msqrt><mrow><mi>n</mi><mi>p</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow></mrow></msqrt><mo>=</mo><msqrt><mrow><mrow><mo>(</mo></mrow><mn>150</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mrow><mn>0</mn><mo>.</mo><mn>08</mn></mrow><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mrow><mn>0</mn><mo>.</mo><mn>92</mn></mrow><mrow><mo>)</mo></mrow></mrow></msqrt><mo>=</mo><mrow><mn>3</mn><mo>.</mo><mn>3226</mn></mrow></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_218'] = '<math display=\'block\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mrow><mo>)</mo></mrow><mo>=</mo><mi>P</mi><mrow><mo>(</mo></mrow><mfrac><mrow><mi>X</mi><mo>&#x2212;</mo><mn>12</mn></mrow><mrow><mrow><mn>3</mn><mo>.</mo><mn>3226</mn></mrow></mrow></mfrac><mo>&#x2264;</mo><mfrac><mrow><mn>10</mn><mo>&#x2212;</mo><mn>12</mn></mrow><mrow><mrow><mn>3</mn><mo>.</mo><mn>3226</mn></mrow></mrow></mfrac><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_219'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mrow><mo>)</mo></mrow><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>3384</mn></mrow></math>';
MathJaxMap['math_220'] = '<math display=\'inline\'><mi>n</mi><mi>p</mi><mo>=</mo><mn>12</mn></math>';
MathJaxMap['math_221'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_222'] = '<math display=\'inline\'><mi>X</mi><mo>=</mo><mn>10</mn></math>';
MathJaxMap['math_223'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_224'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mrow><mn>10</mn><mo>.</mo><mn>5</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_225'] = '<math display=\'inline\'><mi>X</mi><mo>=</mo><mn>10</mn></math>';
MathJaxMap['math_226'] = '<math display=\'inline\'><mo>&#x007B;</mo><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mo>&#x007D;</mo></math>';
MathJaxMap['math_227'] = '<math display=\'inline\'><mi>X</mi><mo>=</mo><mn>10</mn></math>';
MathJaxMap['math_228'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_229'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mrow><mn>10</mn><mo>.</mo><mn>5</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_230'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x003C;</mo><mn>10</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_231'] = '<math display=\'inline\'><mi>X</mi><mo>=</mo><mn>10</mn></math>';
MathJaxMap['math_232'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mrow><mn>9</mn><mo>.</mo><mn>5</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_233'] = '<math display=\'block\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>10</mn><mrow><mo>)</mo></mrow><mo>=</mo><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mrow><mn>10</mn><mo>.</mo><mn>5</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_234'] = '<math display=\'block\'><mo>=</mo><mi>P</mi><mrow><mo>(</mo></mrow><mfrac><mrow><mi>X</mi><mo>&#x2212;</mo><mn>12</mn></mrow><mrow><mrow><mn>3</mn><mo>.</mo><mn>3226</mn></mrow></mrow></mfrac><mo>&#x2264;</mo><mfrac><mrow><mrow><mn>10</mn><mo>.</mo><mn>5</mn></mrow><mo>&#x2212;</mo><mn>12</mn></mrow><mrow><mrow><mn>3</mn><mo>.</mo><mn>3226</mn></mrow></mrow></mfrac><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_235'] = '<math display=\'block\'><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable><mrow><mo>)</mo></mrow><mo>=</mo><mfrac><mrow><mi>n</mi><mo>!</mo></mrow><mrow><mrow><mi>k</mi><mo>!</mo><mo>(</mo><mi>n</mi></mrow><mo>&#x2212;</mo><mrow><mi>k</mi><mo>)</mo><mo>!</mo></mrow></mrow></mfrac><mfrac><mrow/><mrow/></mfrac></math>';
MathJaxMap['math_236'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mn>5</mn></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mn>2</mn></mstyle></mtd></mtr></mtable><mrow><mo>)</mo></mrow></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mn>5</mn><mo>!</mo></mrow></mrow><mrow><mrow><mn>2</mn><mo>!</mo><mn>3</mn><mo>!</mo></mrow></mrow></mfrac><mfrac><mrow/><mrow/></mfrac></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mo>(</mo></mrow><mn>5</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>4</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>3</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>2</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>1</mn><mrow><mo>)</mo></mrow></mrow><mrow><mrow><mo>(</mo></mrow><mn>2</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>1</mn><mrow><mo>)</mo></mrow><mo>&#xd7;</mo><mrow><mo>(</mo></mrow><mn>3</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>2</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>1</mn><mrow><mo>)</mo></mrow></mrow></mfrac></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><mrow><mo>(</mo></mrow><mn>5</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>4</mn><mrow><mo>)</mo></mrow></mrow><mrow><mrow><mo>(</mo></mrow><mn>2</mn><mrow><mo>)</mo></mrow><mrow><mo>(</mo></mrow><mn>1</mn><mrow><mo>)</mo></mrow></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>20</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>=</mo><mn>10</mn></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_237'] = '<math display=\'inline\'><mo>(</mo><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable><mo>)</mo></math>';
MathJaxMap['math_238'] = '<math display=\'inline\'><mfrac><mrow><mi>n</mi></mrow><mrow><mi>k</mi></mrow></mfrac></math>';
MathJaxMap['math_239'] = '<math display=\'inline\'><mo>(</mo><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable><mo>)</mo></math>';
MathJaxMap['math_240'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>=</mo><mi>k</mi><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_241'] = '<math display=\'block\'><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>=</mo><mi>k</mi></mrow><mo>)</mo></mrow><mo>=</mo><mrow><mo>(</mo><mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable></mrow><mo>)</mo></mrow><msup><mi>p</mi><mi>k</mi></msup><msup><mrow><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mrow><mi>n</mi><mo>&#x2212;</mo><mi>k</mi></mrow></msup></mrow></math>';
MathJaxMap['math_242'] = '<math display=\'inline\'><mi>B</mi><mrow><mo>(</mo></mrow><mrow><mn>15</mn><mo>,</mo><mn>0</mn><mo>.</mo><mn>08</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_243'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>&#x2264;</mo><mn>1</mn></mrow><mo>)</mo></mrow></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>=</mo><mn>0</mn></mrow><mo>)</mo></mrow><mo>+</mo><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>=</mo><mn>1</mn></mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mo>(</mo><mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mrow><mn>15</mn></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mn>0</mn></mstyle></mtd></mtr></mtable></mrow><mo>)</mo></mrow><msup><mrow><mo>(</mo><mrow><mn>0.08</mn></mrow><mo>)</mo></mrow><mn>0</mn></msup><msup><mrow><mo>(</mo><mrow><mn>0.92</mn></mrow><mo>)</mo></mrow><mrow><mn>15</mn></mrow></msup><mo>+</mo><mrow><mo>(</mo><mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mrow><mn>15</mn></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mn>1</mn></mstyle></mtd></mtr></mtable></mrow><mo>)</mo></mrow><msup><mrow><mo>(</mo><mrow><mn>0.08</mn></mrow><mo>)</mo></mrow><mn>1</mn></msup><msup><mrow><mo>(</mo><mrow><mn>0.92</mn></mrow><mo>)</mo></mrow><mrow><mn>14</mn></mrow></msup></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><mn>15</mn><mo>!</mo></mrow><mrow><mn>0</mn><mo>!</mo><mn>15</mn><mo>!</mo></mrow></mfrac><mrow><mo>(</mo><mn>1</mn><mo>)</mo></mrow><mrow><mo>(</mo><mrow><mn>0.2863</mn></mrow><mo>)</mo></mrow><mo>+</mo><mfrac><mrow><mn>15</mn><mo>!</mo></mrow><mrow><mn>1</mn><mo>!</mo><mn>14</mn><mo>!</mo></mrow></mfrac><mrow><mo>(</mo><mrow><mn>0.08</mn></mrow><mo>)</mo></mrow><mrow><mo>(</mo><mrow><mn>0.3112</mn></mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mo>(</mo><mn>1</mn><mo>)</mo></mrow><mrow><mo>(</mo><mn>1</mn><mo>)</mo></mrow><mrow><mo>(</mo><mrow><mn>0.2863</mn></mrow><mo>)</mo></mrow><mo>+</mo><mrow><mo>(</mo><mrow><mn>15</mn></mrow><mo>)</mo></mrow><mrow><mo>(</mo><mrow><mn>0.08</mn></mrow><mo>)</mo></mrow><mrow><mo>(</mo><mrow><mn>0.3112</mn></mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mn>0.2863</mn><mo>+</mo><mn>0.3734</mn><mo>=</mo><mn>0.6597</mn></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_244'] = '<math display=\'inline\'><mrow><msup><mi>a</mi><mn>0</mn></msup></mrow><mo>=</mo><mn>1</mn></math>';
MathJaxMap['math_245'] = '<math display=\'inline\'><mi>a</mi><mo>&#x2260;</mo><mn>0</mn></math>';
MathJaxMap['math_246'] = '<math display=\'block\'><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>=</mo><mi>k</mi></mrow><mo>)</mo></mrow><mo>=</mo><mfrac><mrow><msup><mi>e</mi><mrow><mo>&#x2212;</mo><mi>&#x03BC;</mi></mrow></msup><msup><mi>&#x03BC;</mi><mi>k</mi></msup></mrow><mrow><mi>k</mi><mo>!</mo></mrow></mfrac></mrow></math>';
MathJaxMap['math_247'] = '<math display=\'inline\'><msqrt><mrow><mi>&#x03BC;</mi></mrow></msqrt><mo>.</mo></math>';
MathJaxMap['math_248'] = '<math display=\'inline\'><mi>&#x03BC;</mi><mo>=</mo><mrow><mn>2</mn><mo>.</mo><mn>1</mn><mo>.</mo></mrow></math>';
MathJaxMap['math_249'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>2</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_250'] = '<math display=\'block\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>2</mn><mrow><mo>)</mo></mrow><mo>=</mo><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>=</mo><mn>0</mn><mrow><mo>)</mo></mrow><mo>+</mo><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>=</mo><mn>1</mn><mrow><mo>)</mo></mrow><mo>+</mo><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>=</mo><mn>2</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_251'] = '<math display=\'block\'><mrow><mo>=</mo><mfrac><mrow><msup><mi>e</mi><mrow><mo>&#x2212;</mo><mn>2.1</mn></mrow></msup><msup><mrow><mrow><mo>(</mo><mrow><mn>2.1</mn></mrow><mo>)</mo></mrow></mrow><mn>0</mn></msup></mrow><mrow><mn>0</mn><mo>!</mo></mrow></mfrac><mo>+</mo><mfrac><mrow><msup><mi>e</mi><mrow><mo>&#x2212;</mo><mn>2.1</mn></mrow></msup><msup><mrow><mrow><mo>(</mo><mrow><mn>2.1</mn></mrow><mo>)</mo></mrow></mrow><mn>1</mn></msup></mrow><mrow><mn>1</mn><mo>!</mo></mrow></mfrac><mo>+</mo><mfrac><mrow><msup><mi>e</mi><mrow><mo>&#x2212;</mo><mn>2.1</mn></mrow></msup><msup><mrow><mrow><mo>(</mo><mrow><mn>2.1</mn></mrow><mo>)</mo></mrow></mrow><mn>2</mn></msup></mrow><mrow><mn>2</mn><mo>!</mo></mrow></mfrac></mrow></math>';
MathJaxMap['math_252'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>=</mo><mi>k</mi><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_253'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mi>k</mi><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_254'] = '<math display=\'inline\'><mi>&#x03BC;</mi><mo>=</mo><mrow><mn>17</mn><mo>.</mo><mn>2</mn></mrow></math>';
MathJaxMap['math_255'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x003E;</mo><mn>25</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_256'] = '<math display=\'block\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x003E;</mo><mn>25</mn><mrow><mo>)</mo></mrow><mo>=</mo><mn>1</mn><mo>&#x2212;</mo><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>25</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_257'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>25</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_258'] = '<math display=\'inline\'><msub><mi>&#x03BC;</mi><mi>X</mi></msub></math>';
MathJaxMap['math_259'] = '<math display=\'inline\'><msub><mi>&#x03BC;</mi><mi>Y</mi></msub></math>';
MathJaxMap['math_260'] = '<math display=\'inline\'><mi>X</mi><mo>+</mo><mi>Y</mi></math>';
MathJaxMap['math_261'] = '<math display=\'inline\'><msub><mi>&#x03BC;</mi><mi>X</mi></msub><mo>+</mo><msub><mi>&#x03BC;</mi><mi>Y</mi></msub><mo>.</mo></math>';
MathJaxMap['math_262'] = '<math display=\'inline\'><mn>20</mn><mo>&#xd7;</mo><mrow><mn>8</mn><mo>.</mo><mn>9</mn></mrow><mo>=</mo><mrow><mn>178</mn><mo>.</mo></mrow></math>';
MathJaxMap['math_263'] = '<math display=\'inline\'><mrow><mn>0</mn><mo>.</mo><mn>5</mn></mrow><mo>&#xd7;</mo><mrow><mn>4</mn><mo>.</mo><mn>9</mn></mrow><mo>=</mo><mrow><mn>2</mn><mo>.</mo><mn>45</mn><mo>.</mo></mrow></math>';
MathJaxMap['math_264'] = '<math display=\'inline\'><mn>500</mn><mo>&#xd7;</mo><mrow><mn>8</mn><mo>.</mo><mn>9</mn></mrow><mo>=</mo><mrow><mn>4450</mn><mo>.</mo></mrow></math>';
MathJaxMap['math_265'] = '<math display=\'inline\'><mn>2</mn><mo>&#xd7;</mo><mrow><mn>8</mn><mo>.</mo><mn>9</mn></mrow><mo>+</mo><mn>5</mn><mo>&#xd7;</mo><mrow><mn>4</mn><mo>.</mo><mn>9</mn></mrow><mo>=</mo><mrow><mn>42</mn><mo>.</mo><mn>3</mn><mo>.</mo></mrow></math>';
MathJaxMap['math_266'] = '<math display=\'inline\'><msqrt><mrow><mi>&#x03BC;</mi></mrow></msqrt></math>';
MathJaxMap['math_267'] = '<math display=\'inline\'><mn>7</mn><mo>&#xd7;</mo><mn>12</mn><mo>=</mo><mrow><mn>84</mn><mo>.</mo></mrow></math>';
MathJaxMap['math_268'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'right\'><mstyle displaystyle=\'true\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x003E;</mo><mn>100</mn><mrow><mo>)</mo></mrow></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>P</mi><mrow><mo>(</mo></mrow><mfrac><mrow><mi>X</mi><mo>&#x2212;</mo><mn>84</mn></mrow><mrow><msqrt><mrow><mn>84</mn></mrow></msqrt></mrow></mfrac><mo>&#x003E;</mo><mfrac><mrow><mn>100</mn><mo>&#x2212;</mo><mn>84</mn></mrow><mrow><msqrt><mrow><mn>84</mn></mrow></msqrt></mrow></mfrac><mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>Z</mi><mo>&#x003E;</mo><mrow><mn>1</mn><mo>.</mo><mn>75</mn></mrow><mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mn>1</mn><mo>&#x2212;</mo><mi>P</mi><mrow><mo>(</mo></mrow><mi>Z</mi><mo>&#x003C;</mo><mrow><mn>1</mn><mo>.</mo><mn>75</mn></mrow><mrow><mo>)</mo></mrow></mstyle></mtd></mtr><mtr><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0</mn><mo>.</mo><mn>9599</mn></mrow><mo>=</mo><mrow><mn>0</mn><mo>.</mo><mn>0401</mn></mrow></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_269'] = '<math display=\'inline\'><mi>n</mi><mi>p</mi><mo>&#x2265;</mo><mn>10</mn></math>';
MathJaxMap['math_270'] = '<math display=\'inline\'><mi>n</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow><mo>&#x2265;</mo><mn>10</mn></math>';
MathJaxMap['math_271'] = '<math display=\'inline\'><mi>n</mi><mi>p</mi><mo>&#x003C;</mo><mn>10</mn></math>';
MathJaxMap['math_272'] = '<math display=\'inline\'><mi>&#x03BC;</mi><mo>=</mo><mi>n</mi><mi>p</mi></math>';
MathJaxMap['math_273'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2264;</mo><mn>2</mn><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_274'] = '<math display=\'inline\'><mi>B</mi><mrow><mo>(</mo></mrow><mrow><mn>1000</mn><mo>,</mo><mi>&#x00A0;</mi><mo>.</mo><mn>001</mn></mrow><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_275'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_276'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_277'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_278'] = '<math display=\'inline\'><mrow><msub><mi>&#x03BC;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>p</mi></mrow></math>';
MathJaxMap['math_279'] = '<math display=\'block\'><mrow><msub><mi>&#x03C3;</mi><mi>X</mi></msub><mo>=</mo><msqrt><mrow><mi>n</mi><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow></msqrt><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><mtext>&#x2009;</mtext><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mi>n</mi></mfrac></mrow></msqrt></mrow></math>';
MathJaxMap['math_280'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_281'] = '<math display=\'inline\'><mi>B</mi><mrow><mo>(</mo></mrow><mi>n</mi><mo>,</mo><mi>p</mi><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_282'] = '<math display=\'block\'><mrow><mi>X</mi><mtext>&#x2009;</mtext><mtext>is</mtext><mtext>&#x2009;</mtext><mtext>approximately</mtext><mtext>&#x2009;</mtext><mi>N</mi><mrow><mo>(</mo><mrow><mi>n</mi><mi>p</mi><mo>,</mo><msqrt><mrow><mi>n</mi><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow></msqrt></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_283'] = '<math display=\'block\'><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mtext>&#x2009;</mtext><mtext>is</mtext><mtext>&#x2009;</mtext><mtext>approximately</mtext><mtext>&#x2009;</mtext><mi>N</mi><mrow><mo>(</mo><mrow><mi>p</mi><mo>,</mo><mtext>&#x2009;</mtext><msqrt><mrow><mfrac><mrow><mi>p</mi><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mi>n</mi></mfrac></mrow></msqrt></mrow><mo>)</mo></mrow></mrow></math>';
MathJaxMap['math_284'] = '<math display=\'inline\'><mi>n</mi><mi>p</mi><mo>&#x2265;</mo><mn>10</mn></math>';
MathJaxMap['math_285'] = '<math display=\'inline\'><mi>n</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow><mo>&#x2265;</mo><mn>10</mn></math>';
MathJaxMap['math_286'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_287'] = '<math display=\'block\'><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>=</mo><mi>k</mi></mrow><mo>)</mo></mrow><mo>=</mo><mrow><mo>(</mo><mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable></mrow><mo>)</mo></mrow><msup><mi>p</mi><mi>k</mi></msup><msup><mrow><mrow><mo>(</mo><mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi></mrow><mo>)</mo></mrow></mrow><mrow><mi>n</mi><mo>&#x2212;</mo><mi>k</mi></mrow></msup></mrow></math>';
MathJaxMap['math_288'] = '<math display=\'block\'><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable><mo>)</mo><mo>=</mo><mfrac><mrow><mi>n</mi><mo>!</mo></mrow><mrow><mi>k</mi><mo>!</mo><mrow><mo>(</mo></mrow><mi>n</mi><mo>&#x2212;</mo><mi>k</mi><mrow><mo>)</mo></mrow><mo>!</mo></mrow></mfrac></math>';
MathJaxMap['math_289'] = '<math display=\'block\'><mi>n</mi><mo>!</mo><mo>=</mo><mi>n</mi><mo>&#xd7;</mo><mrow><mo>(</mo></mrow><mi>n</mi><mo>&#x2212;</mo><mn>1</mn><mrow><mo>)</mo></mrow><mo>&#xd7;</mo><mrow><mo>(</mo></mrow><mi>n</mi><mo>&#x2212;</mo><mn>2</mn><mrow><mo>)</mo></mrow><mo>&#xd7;</mo><mrow><mo>.</mo><mi>&#x00A0;</mi><mo>.</mo><mi>&#x00A0;</mi><mo>.</mo></mrow><mo>&#xd7;</mo><mn>3</mn><mo>&#xd7;</mo><mn>2</mn><mo>&#xd7;</mo><mn>1</mn></math>';
MathJaxMap['math_290'] = '<math display=\'inline\'><msqrt><mrow><mi>&#x03BC;</mi></mrow></msqrt></math>';
MathJaxMap['math_291'] = '<math display=\'block\'><mrow><mi>P</mi><mrow><mo>(</mo><mrow><mi>X</mi><mo>=</mo><mi>k</mi></mrow><mo>)</mo></mrow><mo>=</mo><mfrac><mrow><msup><mi>e</mi><mrow><mo>&#x2212;</mo><mi>&#x03BC;</mi></mrow></msup><msup><mi>&#x03BC;</mi><mi>k</mi></msup></mrow><mrow><mi>k</mi><mo>!</mo></mrow></mfrac><mtext>&#x2009;</mtext><mi>k</mi><mo>=</mo><mn>0</mn><mo>,</mo><mtext>&#x2009;</mtext><mn>1</mn><mo>,</mo><mtext>&#x2009;</mtext><mn>2</mn><mo>,</mo><mtext>&#x2009;</mtext><mn>3</mn><mo>,</mo><mtext>&#x2009;</mtext><mn>...</mn></mrow></math>';
MathJaxMap['math_292'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_293'] = '<math display=\'inline\'><msqrt><mrow><mi>p</mi><mrow><mo>(</mo></mrow><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mrow><mo>)</mo></mrow><mo>/</mo><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_294'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_295'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_296'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2265;</mo><mi>m</mi><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_297'] = '<math display=\'inline\'><mi>P</mi><mrow><mo>(</mo></mrow><mi>X</mi><mo>&#x2265;</mo><mi>m</mi><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_298'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_299'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_300'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_301'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_302'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_303'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_304'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_305'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_306'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_307'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_308'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_309'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_310'] = '<math display=\'inline\'><mrow><msub><mi>&#x03C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mn>0.005</mn></mrow></math>';
MathJaxMap['math_311'] = '<math display=\'inline\'><mover><mrow><mi>p</mi></mrow><mrow><mo>&#x005E;</mo></mrow></mover></math>';
MathJaxMap['math_312'] = '<math display=\'inline\'><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr></mtable><mrow><mo>)</mo></mrow><mo>=</mo><mn>1</mn></math>';
MathJaxMap['math_313'] = '<math display=\'inline\'><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi><mo>&#x2212;</mo><mn>1</mn></mstyle></mtd></mtr></mtable><mrow><mo>)</mo></mrow><mo>=</mo><mi>n</mi></math>';
MathJaxMap['math_314'] = '<math display=\'inline\'><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>k</mi></mstyle></mtd></mtr></mtable><mrow><mo>)</mo></mrow><mo>=</mo><mrow><mo>(</mo></mrow><mtable><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi></mstyle></mtd></mtr><mtr><mtd><mstyle displaystyle=\'true\'><mi>n</mi><mo>&#x2212;</mo><mi>k</mi></mstyle></mtd></mtr></mtable><mrow><mo>)</mo></mrow></math>';
MathJaxMap['math_315'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_316'] = '<math display=\'inline\'><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_317'] = '<math display=\'inline\'><mover accent=\'true\'><mi>y</mi><mo>&#x00AF;</mo></mover></math>';
MathJaxMap['math_318'] = '<math display=\'inline\'><mrow><mover accent=\'true\'><mi>y</mi><mo>&#x00AF;</mo></mover><mo>&#x2212;</mo><mover accent=\'true\'><mi>x</mi><mo>&#x00AF;</mo></mover></mrow></math>';
MathJaxMap['math_319'] = '<math display=\'inline\'><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mi>F</mi></msub></mrow></math>';
MathJaxMap['math_320'] = '<math display=\'inline\'><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mi>M</mi></msub></mrow></math>';
MathJaxMap['math_321'] = '<math display=\'inline\'><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mi>M</mi></msub></mrow><mo>&#x2212;</mo><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mi>F</mi></msub></mrow></math>';
MathJaxMap['math_322'] = '<math display=\'inline\'><msub><mi>&#x03BC;</mi><mi>X</mi></msub></math>';
MathJaxMap['math_323'] = '<math display=\'inline\'><msub><mi>&#x03BC;</mi><mi>Y</mi></msub></math>';
MathJaxMap['math_324'] = '<math display=\'inline\'><mrow><msubsup><mi>&#x03C3;</mi><mi>X</mi><mn>2</mn></msubsup></mrow></math>';
MathJaxMap['math_325'] = '<math display=\'inline\'><mrow><msubsup><mi>&#x03C3;</mi><mi>Y</mi><mn>2</mn></msubsup></mrow></math>';
MathJaxMap['math_326'] = '<math display=\'inline\'><mi>X</mi><mo>+</mo><mi>Y</mi></math>';
MathJaxMap['math_327'] = '<math display=\'inline\'><msub><mi>&#x03BC;</mi><mi>X</mi></msub><mo>+</mo><msub><mi>&#x03BC;</mi><mi>Y</mi></msub></math>';
MathJaxMap['math_328'] = '<math display=\'inline\'><mrow><msubsup><mi>&#x03C3;</mi><mi>X</mi><mn>2</mn></msubsup></mrow><mo>+</mo><mrow><msubsup><mi>&#x03C3;</mi><mi>Y</mi><mn>2</mn></msubsup></mrow></math>';



for (var key in MathJaxMap) {
  
  if (MathJaxMap.hasOwnProperty(key)) {
    $('[data-math=' + key + ']').html(MathJaxMap[key]);
  }
}

$.ajaxSetup({
  cache: true
});

//configure the mathjax engine
window.MathJax = {
	"HTML-CSS": {
		mtextFontInherit: true,
		scale: 98,
		minScaleAdjust: 100,
		noReflows:false 
	},
	MathML: {
		useMathMLspacing: false
	},
	menuSettings: {
		zoom: "Click"	
	},
	MathMenu: {
		showFontMenu: true
	}
	
  };

$.getScript( "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"); 
