var MathJaxMap = {};


MathJaxMap['math_1'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_2'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.48</mn><mi>.</mi></mrow></math>';
MathJaxMap['math_3'] = '<math display=\'inline\'><mi>X</mi><mo>=</mo><mi>n</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mn>1896</mn><mo>(</mo><mrow><mn>0.48</mn></mrow><mo>)</mo><mo>=</mo><mrow><mn>910</mn><mi>.</mi></mrow></math>';
MathJaxMap['math_4'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_5'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_6'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_7'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_8'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_9'] = '<math display=\'inline\'><msub><mi>&#x3BC;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>p</mi></math>';
MathJaxMap['math_10'] = '<math display=\'inline\'><msub><mi>&#x3C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo><mo>/</mo><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_11'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_12'] = '<math display=\'inline\'><mn>2</mn><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo><mo>/</mo><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_13'] = '<math display=\'inline\'><msub><mi>&#x3C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_14'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_15'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><mi>X</mi></mrow><mrow><mi>n</mi></mrow></mfrac></math>';
MathJaxMap['math_16'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_17'] = '<math display=\'block\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_18'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_19'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>&#xB1;</mo><mi>m</mi></math>';
MathJaxMap['math_20'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><mi>X</mi></mrow><mrow><mi>n</mi></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>910</mn></mrow><mrow><mn>1896</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.47996</mn></mrow></math>';
MathJaxMap['math_21'] = '<math display=\'block\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt><mo>=</mo><msqrt><mrow><mfrac><mrow><mrow><mn>0.47996</mn></mrow><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.47996</mn></mrow><mo>)</mo></mrow><mrow><mn>1896</mn></mrow></mfrac></mrow></msqrt><mo>=</mo><mrow><mn>0.011474</mn></mrow></math>';
MathJaxMap['math_22'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mrow><mn>1.96</mn></mrow><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mo>(</mo><mrow><mn>1.96</mn></mrow><mo>)</mo><mo>(</mo><mrow><mn>0.011474</mn></mrow><mo>)</mo><mo>=</mo><mrow><mn>0.022489</mn></mrow></math>';
MathJaxMap['math_23'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>&#xB1;</mo><mi>m</mi><mo>=</mo><mrow><mn>0.480</mn></mrow><mo>&#xB1;</mo><mrow><mn>0.022</mn></mrow></math>';
MathJaxMap['math_24'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.47996</mn></mrow></math>';
MathJaxMap['math_25'] = '<math display=\'inline\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_26'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_27'] = '<math display=\'inline\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_28'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_29'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mo>=</mo><mfrac><mrow><mi>X</mi><mo>&#x2B;</mo><mn>2</mn></mrow><mrow><mi>n</mi><mo>&#x2B;</mo><mn>4</mn></mrow></mfrac></math>';
MathJaxMap['math_30'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mi>.</mi></math>';
MathJaxMap['math_31'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover></math>';
MathJaxMap['math_32'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover></math>';
MathJaxMap['math_33'] = '<math display=\'inline\'><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo><mo>/</mo><mo>(</mo><mi>n</mi><mo>&#x2B;</mo><mn>4</mn><mo>)</mo></mrow></msqrt></math>';
MathJaxMap['math_34'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover></math>';
MathJaxMap['math_35'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mi>.</mi></math>';
MathJaxMap['math_36'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mo>=</mo><mfrac><mrow><mn>4</mn><mo>&#x2B;</mo><mn>2</mn></mrow><mrow><mn>12</mn><mo>&#x2B;</mo><mn>4</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>6</mn></mrow><mrow><mn>16</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.375</mn></mrow></math>';
MathJaxMap['math_37'] = '<math display=\'block\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mo>)</mo></mrow><mrow><mi>n</mi><mo>&#x2B;</mo><mn>4</mn></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_38'] = '<math display=\'block\'><mo>=</mo><msqrt><mrow><mfrac><mrow><mo>(</mo><mrow><mn>0.375</mn></mrow><mo>)</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.375</mn></mrow><mo>)</mo></mrow><mrow><mn>16</mn></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_39'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover></msub></math>';
MathJaxMap['math_40'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mo>&#xB1;</mo><mi>m</mi><mo>=</mo><mrow><mn>0.375</mn></mrow><mo>&#xB1;</mo><mrow><mn>0.237</mn></mrow></math>';
MathJaxMap['math_41'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_42'] = '<math display=\'inline\'><msub><mi>&#x3BC;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>p</mi></math>';
MathJaxMap['math_43'] = '<math display=\'inline\'><msub><mi>&#x3C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo><mo>/</mo><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_44'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_45'] = '<math display=\'inline\'><msub><mi>&#x3C3;</mi><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_46'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_47'] = '<math display=\'block\'><mi>z</mi><mo>=</mo><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>&#x2212;</mo><msub><mi>p</mi><mn>0</mn></msub></mrow><mrow><msqrt><mrow><mfrac><mrow><msub><mi>p</mi><mn>0</mn></msub><mrow><mo>(</mo><mn>1</mn></mrow><mo>&#x2212;</mo><msub><mi>p</mi><mn>0</mn></msub><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt></mrow></mfrac></math>';
MathJaxMap['math_48'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><mi>X</mi></mrow><mrow><mi>n</mi></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>13</mn></mrow><mrow><mn>20</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.65</mn></mrow></math>';
MathJaxMap['math_49'] = '<math display=\'block\'><mi>z</mi><mo>=</mo><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>&#x2212;</mo><msub><mi>p</mi><mn>0</mn></msub></mrow><mrow><msqrt><mrow><mfrac><mrow><msub><mi>p</mi><mn>0</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>0</mn></msub><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt></mrow></mfrac><mo>=</mo><mfrac><mrow><mrow><mn>0.65</mn></mrow><mo>&#x2212;</mo><mrow><mn>0.5</mn></mrow></mrow><mrow><msqrt><mrow><mfrac><mrow><mo>(</mo><mrow><mn>0.5</mn></mrow><mo>)</mo><mo>(</mo><mrow><mn>0.5</mn></mrow><mo>)</mo></mrow><mrow><mn>20</mn></mrow></mfrac></mrow></msqrt></mrow></mfrac><mo>=</mo><mrow><mn>1.34</mn></mrow></math>';
MathJaxMap['math_50'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.65</mn></mrow></math>';
MathJaxMap['math_51'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><mi>z</mi><mo>*</mo><msqrt><mrow><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_52'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_53'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_54'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.5</mn></mrow></math>';
MathJaxMap['math_55'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mi>p</mi><mo>*</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>*</mo><mo>)</mo></math>';
MathJaxMap['math_56'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup></math>';
MathJaxMap['math_57'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac><mo>(</mo><mfrac><mrow><mrow><mn>1.96</mn></mrow></mrow><mrow><mrow><mn>0.03</mn></mrow></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>=</mo><mrow><mn>1067.1</mn></mrow></math>';
MathJaxMap['math_58'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac><mo>(</mo><mfrac><mrow><mrow><mn>1.96</mn></mrow></mrow><mrow><mrow><mn>0.025</mn></mrow></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>=</mo><mn>1537</mn></math>';
MathJaxMap['math_59'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac><mo>(</mo><mfrac><mrow><mrow><mn>1.96</mn></mrow></mrow><mrow><mrow><mn>0.02</mn></mrow></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>=</mo><mn>2401</mn></math>';
MathJaxMap['math_60'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_61'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_62'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>m</mi></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></mstyle></mtd></mtr>
<mtr columnalign=\'left\'><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mn>1.96</mn></mrow><msqrt><mrow><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo></mrow><mrow><mn>200</mn></mrow></mfrac></mrow></msqrt></mstyle></mtd></mtr>
<mtr columnalign=\'left\'><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><mn>0.139</mn></mrow><msqrt><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo></mrow></msqrt></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_63'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_64'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_65'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_66'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.05</mn></mrow></math>';
MathJaxMap['math_67'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.95</mn></mrow></math>';
MathJaxMap['math_68'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_69'] = '<math display=\'inline\'><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_70'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_71'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.5</mn></mrow></math>';
MathJaxMap['math_72'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_73'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_74'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_75'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mn>13</mn><mo>/</mo><mn>20</mn><mo>=</mo><mrow><mn>0.65</mn></mrow></math>';
MathJaxMap['math_76'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_77'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_78'] = '<math display=\'inline\'><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo><mo>/</mo><mi>n</mi></mrow></msqrt></math>';
MathJaxMap['math_79'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_80'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_81'] = '<math display=\'block\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_82'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>&#xB1;</mo><mi>m</mi></math>';
MathJaxMap['math_83'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mi>p</mi><mo>*</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>*</mo><mo>)</mo></math>';
MathJaxMap['math_84'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_85'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>4</mn></mrow></mfrac><mtext>&#x00A0;</mtext><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup></math>';
MathJaxMap['math_86'] = '<math display=\'block\'><mi>z</mi><mo>=</mo><mfrac><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>&#x2212;</mo><msub><mi>p</mi><mn>0</mn></msub></mrow><mrow><msqrt><mrow><mfrac><mrow><msub><mi>p</mi><mn>0</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>0</mn></msub><mo>)</mo></mrow><mrow><mi>n</mi></mrow></mfrac></mrow></msqrt></mrow></mfrac></math>';
MathJaxMap['math_87'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_88'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.3</mn></mrow></math>';
MathJaxMap['math_89'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_90'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_91'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_92'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_93'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>=</mo><msub><mi>X</mi><mn>1</mn></msub><mo>/</mo><msub><mi>n</mi><mn>1</mn></msub></math>';
MathJaxMap['math_94'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>=</mo><msub><mi>X</mi><mn>2</mn></msub><mo>/</mo><msub><mi>n</mi><mn>2</mn></msub></math>';
MathJaxMap['math_95'] = '<math display=\'block\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_96'] = '<math display=\'block\'><msub><mi>&#x3BC;</mi><mi>D</mi></msub><mo>=</mo><msub><mi>&#x3BC;</mi><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></msub><mo>&#x2212;</mo><msub><mi>&#x3BC;</mi><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></msub><mo>=</mo><msub><mi>p</mi><mn>1</mn></msub><mo>&#x2212;</mo><msub><mi>p</mi><mn>2</mn></msub></math>';
MathJaxMap['math_97'] = '<math display=\'inline\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_98'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><msubsup><mi>&#x03C3;</mi><mi>D</mi><mn>2</mn></msubsup></mrow></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mrow><msubsup><mi>&#x03C3;</mi><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></mrow><mn>2</mn></msubsup></mrow><mrow><msubsup><mi>&#x03C3;</mi><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></mrow><mn>2</mn></msubsup></mrow></mstyle></mtd></mtr>
<mtr columnalign=\'left\'><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mfrac><mrow><msub><mi>p</mi><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mi>p</mi><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_99'] = '<math display=\'block\'><msub><mi>&#x3C3;</mi><mi>D</mi></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mi>p</mi><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mi>p</mi><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_100'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></math>';
MathJaxMap['math_101'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_102'] = '<math display=\'inline\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_103'] = '<math display=\'block\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_104'] = '<math display=\'block\'><msub><mtext>SE</mtext><mi>D</mi></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_105'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></msub></math>';
MathJaxMap['math_106'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_107'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_108'] = '<math display=\'block\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_109'] = '<math display=\'block\'><msub><mtext>SE</mtext><mi>D</mi></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_110'] = '<math display=\'block\'><mo>=</mo><msqrt><mrow><mfrac><mrow><mo>(</mo><mrow><mn>0.6108</mn></mrow><mo>)</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.6108</mn></mrow><mo>)</mo></mrow><mrow><mn>537</mn></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mo>(</mo><mrow><mn>0.4398</mn></mrow><mo>)</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.4398</mn></mrow><mo>)</mo></mrow><mrow><mn>532</mn></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_111'] = '<math display=\'block\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>1</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>1</mn></msub><mo>&#x2B;</mo><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>4</mn><mo>&#x2B;</mo><mn>1</mn></mrow><mrow><mn>12</mn><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.3571</mn></mrow></math>';
MathJaxMap['math_112'] = '<math display=\'block\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>2</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>2</mn></msub><mo>&#x2B;</mo><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>3</mn><mo>&#x2B;</mo><mn>1</mn></mrow><mrow><mn>12</mn><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.2857</mn></mrow></math>';
MathJaxMap['math_113'] = '<math display=\'block\'><mover accent=\'true\'><mi>D</mi><mo>&#x02DC;</mo></mover><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>2</mn></msub><mo>=</mo><mrow><mn>0.3571</mn></mrow><mo>&#x2212;</mo><mrow><mn>0.2857</mn></mrow><mo>=</mo><mrow><mn>0.071</mn></mrow></math>';
MathJaxMap['math_114'] = '<math display=\'inline\'><mover accent=\'true\'><mi>D</mi><mo>&#x02DC;</mo></mover></math>';
MathJaxMap['math_115'] = '<math display=\'block\'><msub><mtext>SE</mtext><mover accent=\'true\'><mi>D</mi><mo>&#x02DC;</mo></mover></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x02DC;</mo></mover><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_116'] = '<math display=\'block\'><mo>=</mo><msqrt><mrow><mfrac><mrow><mo>(</mo><mrow><mn>0.3571</mn></mrow><mo>)</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.3571</mn></mrow><mo>)</mo></mrow><mrow><mn>12</mn><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mo>(</mo><mrow><mn>0.2857</mn></mrow><mo>)</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.2857</mn></mrow><mo>)</mo></mrow><mrow><mn>12</mn><mo>&#x2B;</mo><mn>2</mn></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_117'] = '<math display=\'block\'><mi>m</mi><mo>=</mo><mi>z</mi><mo>*</mo><msub><mtext>SE</mtext><mover accent=\'true\'><mi>D</mi><mo>&#x02DC;</mo></mover></msub><mo>=</mo><mo>(</mo><mrow><mn>1.96</mn></mrow><mo>)</mo><mo>(</mo><mrow><mn>0.1760</mn></mrow><mo>)</mo><mo>=</mo><mrow><mn>0.345</mn></mrow></math>';
MathJaxMap['math_118'] = '<math display=\'block\'><mover accent=\'true\'><mi>D</mi><mo>&#x02DC;</mo></mover><mo>&#xB1;</mo><mi>m</mi><mo>=</mo><mrow><mn>0.071</mn></mrow><mo>&#xB1;</mo><mrow><mn>0.345</mn></mrow></math>';
MathJaxMap['math_119'] = '<math display=\'inline\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_120'] = '<math display=\'block\'><msub><mi>&#x3C3;</mi><mi>D</mi></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mi>p</mi><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mi>p</mi><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mi>p</mi><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_121'] = '<math display=\'inline\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_122'] = '<math display=\'block\'><mtable columnalign=\'left\'><mtr columnalign=\'left\'><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msub><mi>&#x3C3;</mi><mi>D</mi></msub></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msqrt><mrow><mfrac><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></mstyle></mtd></mtr>
<mtr columnalign=\'left\'><mtd columnalign=\'left\'/><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><mo>=</mo></mstyle></mtd><mtd columnalign=\'left\'><mstyle displaystyle=\'true\'><msqrt><mrow><mi>p</mi><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mi>p</mi><mo>)</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac><mo>)</mo></mrow></msqrt></mstyle></mtd></mtr></mtable></math>';
MathJaxMap['math_123'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><mrow><mtext>number</mtext><mtext>&#x00A0;</mtext><mtext>of</mtext><mtext>&#x00A0;</mtext><mtext>successes</mtext><mtext>&#x00A0;</mtext><mtext>in</mtext><mtext>&#x00A0;</mtext><mtext>both</mtext><mtext>&#x00A0;</mtext><mtext>samples</mtext></mrow></mrow><mrow><mrow><mtext>number</mtext><mtext>&#x00A0;</mtext><mtext>of</mtext><mtext>&#x00A0;</mtext><mtext>observations</mtext><mtext>&#x00A0;</mtext><mtext>in</mtext><mtext>&#x00A0;</mtext><mtext>both</mtext><mtext>&#x00A0;</mtext><mtext>samples</mtext></mrow></mrow></mfrac><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>1</mn></msub><mo>&#x2B;</mo><msub><mi>X</mi><mn>2</mn></msub></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub><mo>&#x2B;</mo><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_124'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_125'] = '<math display=\'block\'><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow><mo>=</mo><msqrt><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac><mo>)</mo></mrow></msqrt></math>';
MathJaxMap['math_126'] = '<math display=\'block\'><mi>z</mi><mo>=</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></mrow><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow></mfrac></math>';
MathJaxMap['math_127'] = '<math display=\'block\'><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow><mo>=</mo><msqrt><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac><mo>)</mo></mrow></msqrt></math>';
MathJaxMap['math_128'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>1</mn></msub><mo>&#x2B;</mo><msub><mi>X</mi><mn>2</mn></msub></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub><mo>&#x2B;</mo><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_129'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_130'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><mn>328</mn><mo>&#x2B;</mo><mn>234</mn></mrow><mrow><mn>537</mn><mo>&#x2B;</mo><mn>532</mn></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>562</mn></mrow><mrow><mn>1069</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.5257</mn></mrow></math>';
MathJaxMap['math_131'] = '<math display=\'block\'><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow><mo>=</mo><msqrt><mrow><mo>(</mo><mrow><mn>0.5257</mn></mrow><mo>)</mo><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mrow><mn>0.5257</mn></mrow><mo>)</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>537</mn></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>532</mn></mrow></mfrac><mo>)</mo></mrow></msqrt><mo>=</mo><mrow><mn>0.03055</mn></mrow></math>';
MathJaxMap['math_132'] = '<math display=\'block\'><mi>z</mi><mo>=</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></mrow><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow></mfrac><mo>=</mo><mfrac><mrow><mrow><mn>0.6108</mn></mrow><mo>&#x2212;</mo><mrow><mn>0.4398</mn></mrow></mrow><mrow><mrow><mn>0.03055</mn></mrow></mrow></mfrac></math>';
MathJaxMap['math_133'] = '<math display=\'block\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>1</mn></msub></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2212;</mo><mfrac><mrow><msub><mi>X</mi><mn>2</mn></msub></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_134'] = '<math display=\'block\'><msub><mtext>SE</mtext><mi>D</mi></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_135'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>(</mo><msubsup><mi>p</mi><mo>1</mo><mn>*</mn></msubsup><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msubsup><mi>p</mi><mo>1</mo><mn>*</mn></msubsup><mo>)</mo><mo>&#x2B;</mo><msubsup><mi>p</mi><mo>2</mo><mn>*</mn></msubsup><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msubsup><mi>p</mi><mo>2</mo><mn>*</mn></msubsup><mo>)</mo><mo>)</mo></math>';
MathJaxMap['math_136'] = '<math display=\'inline\'><mi>p</mi><msub><mo>*</mo><mn>1</mn></msub></math>';
MathJaxMap['math_137'] = '<math display=\'inline\'><mi>p</mi><msub><mo>*</mo><mn>2</mn></msub></math>';
MathJaxMap['math_138'] = '<math display=\'inline\'><mi>p</mi><msub><mo>*</mo><mn>1</mn></msub></math>';
MathJaxMap['math_139'] = '<math display=\'inline\'><mi>p</mi><msub><mo>*</mo><mn>2</mn></msub></math>';
MathJaxMap['math_140'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>)</mo><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup></math>';
MathJaxMap['math_141'] = '<math display=\'block\'><mi>n</mi><mo>=</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>)</mo><mo>(</mo><mfrac><mrow><mi>z</mi><mo>*</mo></mrow><mrow><mi>m</mi></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>=</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mo>)</mo><mo>(</mo><mfrac><mrow><mrow><mn>1.96</mn></mrow></mrow><mrow><mrow><mn>0.1</mn></mrow></mrow></mfrac><msup><mo>)</mo><mn>2</mn></msup><mo>=</mo><mrow><mn>192.08</mn></mrow></math>';
MathJaxMap['math_142'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></math>';
MathJaxMap['math_143'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_144'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mi>X</mi><mo>/</mo><mi>n</mi></math>';
MathJaxMap['math_145'] = '<math display=\'block\'><mtext>RR</mtext><mo>=</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></mrow><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>45</mn><mo>/</mo><mn>411</mn></mrow><mrow><mn>73</mn><mo>/</mo><mn>411</mn></mrow></mfrac><mo>=</mo><mrow><mn>0.6164</mn></mrow></math>';
MathJaxMap['math_146'] = '<math display=\'block\'><mi>D</mi><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_147'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></math>';
MathJaxMap['math_148'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_149'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>1</mn></msub></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_150'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>2</mn></msub></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_151'] = '<math display=\'block\'><msub><mtext>SE</mtext><mi>D</mi></msub><mo>=</mo><msqrt><mrow><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>)</mo></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></mrow></msqrt></math>';
MathJaxMap['math_152'] = '<math display=\'block\'><mi>z</mi><mo>=</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>&#x2212;</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></mrow><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow></mfrac></math>';
MathJaxMap['math_153'] = '<math display=\'block\'><mrow><mtext>S</mtext><msub><mtext>E</mtext><mrow><mi>D</mi><mi>P</mi></mrow></msub></mrow><mo>=</mo><msqrt><mrow><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>(</mo><mn>1</mn><mo>&#x2212;</mo><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>)</mo><mo>(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub></mrow></mfrac><mo>&#x2B;</mo><mfrac><mrow><mn>1</mn></mrow><mrow><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac><mo>)</mo></mrow></msqrt></math>';
MathJaxMap['math_154'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';
MathJaxMap['math_155'] = '<math display=\'block\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mfrac><mrow><msub><mi>X</mi><mn>1</mn></msub><mo>&#x2B;</mo><msub><mi>X</mi><mn>2</mn></msub></mrow><mrow><msub><mi>n</mi><mn>1</mn></msub><mo>&#x2B;</mo><msub><mi>n</mi><mn>2</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_156'] = '<math display=\'block\'><mtext>RR</mtext><mo>=</mo><mfrac><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></mrow><mrow><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></mrow></mfrac></math>';
MathJaxMap['math_157'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_158'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>=</mo><mrow><mn>0.65</mn></mrow></math>';
MathJaxMap['math_159'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>=</mo><mrow><mn>0.45</mn></mrow></math>';
MathJaxMap['math_160'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub></math>';
MathJaxMap['math_161'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub></math>';
MathJaxMap['math_162'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>=</mo><mrow><mn>0.7</mn></mrow></math>';
MathJaxMap['math_163'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>=</mo><mrow><mn>0.5</mn></mrow></math>';
MathJaxMap['math_164'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mo>=</mo><mrow><mn>0.5</mn></mrow></math>';
MathJaxMap['math_165'] = '<math display=\'inline\'><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>1</mn></msub><mo>=</mo><msub><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover><mn>2</mn></msub><mo>=</mo><mrow><mn>0.5</mn></mrow></math>';
MathJaxMap['math_166'] = '<math display=\'inline\'><mover accent=\'true\'><mi>p</mi><mo>&#x005E;</mo></mover></math>';



for (var key in MathJaxMap) {
  
  if (MathJaxMap.hasOwnProperty(key)) {
    $('[data-math=' + key + ']').html(MathJaxMap[key]);
  }
}

$.ajaxSetup({
  cache: true
});

//configure the mathjax engine
window.MathJax = {
	"HTML-CSS": {
		mtextFontInherit: true,
		scale: 98,
		minScaleAdjust: 100,
		noReflows:false 
	},
	MathML: {
		useMathMLspacing: false
	},
	menuSettings: {
		zoom: "Click"	
	},
	MathMenu: {
		showFontMenu: true
	}
	
  };

$.getScript( "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"); 
